import { readFileSync } from 'node:fs'
import pg from 'pg'

const { Pool } = pg

const databaseUrl = () => {
  if (process.env.PPTIST_DATABASE_URL) return process.env.PPTIST_DATABASE_URL.trim()
  const file = process.env.PPTIST_DATABASE_URL_FILE || '/etc/pptist-cloud/database-url'
  return readFileSync(file, 'utf8').trim()
}

export const createDatabasePool = () => new Pool({
  connectionString: databaseUrl(),
  max: Math.max(1, Math.min(10, Number(process.env.PPTIST_DB_POOL_MAX || 5))),
  connectionTimeoutMillis: 5_000,
  idleTimeoutMillis: 30_000,
  application_name: 'pptist-cloud',
})

export const ensureSchema = async client => {
  await client.query(`
    CREATE TABLE IF NOT EXISTS users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      username TEXT NOT NULL UNIQUE,
      password_hash TEXT NOT NULL,
      disabled BOOLEAN NOT NULL DEFAULT FALSE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );

    CREATE TABLE IF NOT EXISTS sessions (
      token_hash TEXT PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      expires_at TIMESTAMPTZ NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );

    CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions(user_id);
    CREATE INDEX IF NOT EXISTS idx_sessions_expires_at ON sessions(expires_at);

    CREATE TABLE IF NOT EXISTS presentations (
      id UUID PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      title TEXT NOT NULL,
      content_json JSONB NOT NULL,
      media_prefix TEXT,
      slide_count INTEGER NOT NULL DEFAULT 1 CHECK (slide_count > 0),
      revision INTEGER NOT NULL DEFAULT 1 CHECK (revision > 0),
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      deleted_at TIMESTAMPTZ
    );

    ALTER TABLE presentations ADD COLUMN IF NOT EXISTS media_prefix TEXT;

    CREATE INDEX IF NOT EXISTS idx_presentations_user_updated
      ON presentations(user_id, updated_at DESC)
      WHERE deleted_at IS NULL;

    CREATE UNIQUE INDEX IF NOT EXISTS idx_presentations_media_prefix
      ON presentations(media_prefix)
      WHERE media_prefix IS NOT NULL;

    CREATE TABLE IF NOT EXISTS user_media_credentials (
      user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
      encrypted_api_key TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
  `)
}
