export const FONTS = [
  { label: '默认字体', value: '' },
  { label: '思源黑体', value: 'SourceHanSans' },
  { label: '思源宋体', value: 'SourceHanSerif' },
  { label: '文鼎PL楷体', value: 'WenDingPLKaiTi' },
  { label: '文鼎PL宋体', value: 'WenDingPLSongTi' },
  { label: '朱雀仿宋', value: 'ZhuQueFangSong' },
  { label: '霞鹜文楷', value: 'LXGWWenKai' },
  { label: '霞鹜新致宋', value: 'LXGWNeoZhiSong' },
  { label: '霞鹜新晰黑', value: 'LXGWNeoXiHei' },
  { label: '阿里巴巴普惠体', value: 'AlibabaPuHuiTi' },
  { label: '得意黑', value: 'DeYiHei' },
  { label: 'MiSans', value: 'MiSans' },
  { label: 'Source Serif 4', value: 'SourceSerif4' },
  { label: 'JetBrains Mono', value: 'JetBrainsMono' },
  { label: 'Literata', value: 'Literata' },
  { label: 'Inter', value: 'Inter' },
  { label: 'Roboto', value: 'Roboto' },
  { label: 'Open Sans', value: 'OpenSans' },
  { label: 'Montserrat', value: 'Montserrat' },
  { label: 'Source Sans Pro', value: 'SourceSansPro' },
  { label: 'Merriweather', value: 'Merriweather' },
  { label: 'Lato', value: 'Lato' },
  { label: '微软雅黑（系统）', value: 'Microsoft YaHei' },
  { label: '黑体（系统）', value: 'SimHei' },
  { label: '宋体（系统）', value: 'SimSun' },
  { label: '楷体（系统）', value: 'KaiTi' },
  { label: '仿宋（系统）', value: 'FangSong' },
  { label: '等线（系统）', value: 'DengXian' },
  { label: '苹方（系统）', value: 'PingFang SC' },
  { label: '冬青黑体（系统）', value: 'Hiragino Sans GB' },
  { label: '思源黑体 CJK（系统）', value: 'Noto Sans CJK SC' },
  { label: '思源宋体 CJK（系统）', value: 'Noto Serif CJK SC' },
  { label: 'Arial（系统）', value: 'Arial' },
  { label: 'Helvetica（系统）', value: 'Helvetica' },
  { label: 'Times New Roman（系统）', value: 'Times New Roman' },
  { label: 'Georgia（系统）', value: 'Georgia' },
  { label: 'Verdana（系统）', value: 'Verdana' },
  { label: 'Tahoma（系统）', value: 'Tahoma' },
  { label: 'Trebuchet MS（系统）', value: 'Trebuchet MS' },
  { label: 'Courier New（系统）', value: 'Courier New' },
  { label: 'Palatino Linotype（系统）', value: 'Palatino Linotype' },
  { label: 'Garamond（系统）', value: 'Garamond' },
]
